FROM cgr.dev/chainguard/wolfi-base:latest

LABEL com.github.containers.toolbox="true" \
      name="wolfi-toolbox" \
      version="latest" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="Base image for creating Wolfi Linux toolbox containers" \
      maintainer="Luca Di Maio <luca.dimaio1@gmail.com>"

# Install extra packages
COPY extra-packages /
RUN apk update && \
    apk upgrade && \
    cat /extra-packages | xargs apk add
RUN rm /extra-packages

# Enable password less sudo
# using sudoers instead of toolbox filename here, so that in case of rootful
# distroboxes, the NOPASSWD can be deactivated for security reasons.
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudoers

# Copy the os-release file
RUN cp -p /etc/os-release /usr/lib/os-release

# Clear out /home
RUN rm -rf /home/* && mkdir /media
