FROM registry.access.redhat.com/ubi7/ubi

ENV NAME=rhel-toolbox VERSION=7
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating RHEL toolbox containers" \
      maintainer="Timothée Ravier <tim@siosm.fr>"

RUN sed -i '/tsflags=nodocs/d' /etc/yum.conf

COPY missing-docs extra-packages /

RUN yum -y reinstall $(<missing-docs) && \
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum -y install $(<extra-packages) && \
    yum -y upgrade && \
    yum clean all

RUN rm /missing-docs /extra-packages
