FROM registry.access.redhat.com/ubi7/ubi

ENV NAME=rhel-toolbox VERSION=7
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating RHEL 7 toolbox containers" \
      maintainer="Timothée Ravier <tim@siosm.fr>"

RUN sed -i '/tsflags=nodocs/d' /etc/yum.conf

COPY missing-docs /
RUN yum -y reinstall $(<missing-docs)
RUN rm /missing-docs

COPY extra-packages /
RUN yum -y install $(<extra-packages)
RUN rm /extra-packages

RUN yum clean all
