FROM docker.io/library/alpine:3.16

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Alpine Linux toolbox containers" \
      maintainer="Ricardo Arguello <ricado.arguello@gmail.com>"

# Install extra packages
COPY extra-packages /
RUN apk update && \
    apk upgrade && \
    cat /extra-packages | xargs apk add
RUN rm /extra-packages

# Enable password less sudo
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox

# Copy the os-release file
RUN cp -p /etc/os-release /usr/lib/os-release
