FROM registry.fedoraproject.org/fedora:38

ARG NAME=fedora-toolbox
ARG VERSION=38
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Fedora toolbox containers" \
      maintainer="Debarshi Ray <rishi@fedoraproject.org>"

RUN rm /etc/rpm/macros.image-language-conf
RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf

COPY missing-docs extra-packages /

RUN dnf -y upgrade && \
    dnf -y swap coreutils-single coreutils-full && \
    dnf -y swap glibc-minimal-langpack glibc-all-langpacks && \
    dnf -y reinstall $(<missing-docs) && \
    dnf -y install $(<extra-packages) && \
    dnf clean all

RUN rm /missing-docs /extra-packages
