FROM registry.fedoraproject.org/fedora:38

ARG NAME=fedora-toolbox
ARG VERSION=38
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Fedora toolbox containers" \
      maintainer="Debarshi Ray <rishi@fedoraproject.org>"

RUN rm /etc/rpm/macros.image-language-conf
RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf

COPY missing-docs extra-packages ensure-files /

RUN dnf -y upgrade && \
    dnf -y swap coreutils-single coreutils-full && \
    dnf -y swap glibc-minimal-langpack glibc-all-langpacks && \
    dnf -y reinstall $(<missing-docs) && \
    dnf -y install $(<extra-packages) && \
    dnf clean all

RUN ret_val=0; \
  while read file; do \
    if ! compgen -G "$file" >/dev/null; then \
      echo "$file: No such file or directory" >&2; \
      ret_val=1; \
      break; \
    fi; \
  done <ensure-files; \
  if [ "$ret_val" -ne 0 ]; then \
    false; \
  fi

RUN rm /missing-docs /extra-packages /ensure-files
