FROM quay.io/centos/centos:stream9

ENV NAME=centos-toolbox VERSION=stream9
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating CentOS toolbox containers" \
      maintainer="Timothée Ravier <tim@siosm.fr>"

RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf

COPY missing-docs extra-packages /

RUN dnf -y swap coreutils-single coreutils-full && \
    dnf -y reinstall $(<missing-docs) && \
    dnf -y install $(<extra-packages) && \
    dnf -y upgrade && \
    dnf clean all

RUN rm /missing-docs /extra-packages
