# justfile

default:
  @just --summary

help:
  @just --list

alias m := make
make: build create
  
alias b := build
build:
  podman build -t amazonlinux-toolbox:2 -f Containerfile .

alias c := create
create:
  toolbox create -c amazonlinux-toolbox-2 -i amazonlinux-toolbox:2

alias e := enter
enter:
  toolbox enter amazonlinux-toolbox-2

alias cu := cleanup
cleanup:
  podman stop amazonlinux-toolbox-2
  toolbox rm amazonlinux-toolbox-2
  toolbox rmi amazonlinux-toolbox:2
