FROM registry.opensuse.org/opensuse/toolbox:latest

ENV NAME=opensuse-toolbox VERSION=tumbleweed
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating openSUSE toolbox containers" \
      maintainer="Hari Rana <theevilskeleton@fedoraproject.org>"

# Update packages, install extra packages and clean up cache 
COPY extra-packages /
RUN zypper update -y && \
    cat /extra-packages | xargs zypper install -y && \
    zypper clean
RUN rm /extra-packages

# Enable sudo permission for wheel users
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
