FROM registry.opensuse.org/opensuse/toolbox:latest

ENV NAME=opensuse-toolbox VERSION=tumbleweed
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating openSUSE toolbox containers" \
      maintainer="Hari Rana <theevilskeleton@riseup.net>"

# Install extra packages
COPY extra-packages /
RUN zypper update -y && \
    cat /extra-packages | xargs zypper install -y
RUN rm /extra-packages

# Enable password less sudo
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
