FROM public.ecr.aws/amazonlinux/amazonlinux:2023

LABEL com.github.containers.toolbox="true" \
  name="amazonlinux-toolbox" \
  version="2023" \
  usage="This image is meant to be used with the toolbox command" \
  summary="Base image for creating Amazon Linux 2023 toolbox containers" \
  maintainer="Stewart Smith <trawets@amazon.com>"

COPY missing-docs extra-packages /

RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf
RUN dnf -y swap coreutils-single coreutils-full && \
  dnf -y reinstall $(<missing-docs) && \
  dnf -y install --allowerasing $(<extra-packages) && \
  dnf -y upgrade && \
  dnf clean all

RUN sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers
RUN echo 'Defaults lecture="never"' > /etc/sudoers.d/disable-sudo-lecture

RUN echo VARIANT_ID=container >> /etc/os-release

RUN rm /{extra-packages,missing-docs}
